import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * The site title is the client's own name, from their wordmark — not copy.
 *
 * There is deliberately NO `description`. A meta description is a positioning sentence about a
 * forty-year-old jewellery house, and writing one here would be inventing how the business
 * describes itself (hard rule 8). It is seeded empty and `/admin/settings/seo` is where the
 * client writes it; until then search engines compose one from the page, which is honest.
 * Leaving "Generated by create next app" in place would have shipped that to production.
 */
export const metadata: Metadata = {
  title: { default: "MILLENNIUM DESIGNS", template: "%s · MILLENNIUM DESIGNS" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
