// GENERATED by scripts/gen-background-tokens.ts from src/styles/tokens.css.
// Do not edit. Add a surface by declaring it in the stylesheet and in that script's list,
// then re-running the generator and the migration that widens
// chk_cms_sections_background_token.
//
// 11 §7.7: cms_sections.background_token and the background_token field on the banner, cta,
// heritage and newsletter blocks accept exactly these seven values or NULL. A hex value in
// the database is impossible rather than merely forbidden in prose.

export const BACKGROUND_TOKENS = [
  "--md-ivory-soft", // page ground (the default when the section stores NULL)
  "--md-ivory", // raised / alternating band
  "--md-stone", // quiet divider band
  "--md-emerald-deep", // primary dark surface
  "--md-forest", // secondary dark surface
  "--md-green-dark", // deep panel / image scrim base
  "--md-green-black", // near-black ground, full-bleed editorial
] as const;

export type BackgroundToken = (typeof BACKGROUND_TOKENS)[number];

/** The default when a section stores NULL. */
export const DEFAULT_BACKGROUND_TOKEN: BackgroundToken = BACKGROUND_TOKENS[0];

/** The `data-surface` value for a token — the stylesheet keys its surface blocks on this. */
export function surfaceFor(token: BackgroundToken | null): string {
  return (token ?? DEFAULT_BACKGROUND_TOKEN).replace(/^--md-/, "");
}

export function isBackgroundToken(value: string): value is BackgroundToken {
  return (BACKGROUND_TOKENS as readonly string[]).includes(value);
}
