/**
 * Generate `src/lib/cms/backgroundTokens.ts` from `src/styles/tokens.css` — 10 §2.1, 11 §7.7.
 *
 * The CMS stores a section's surface as a token NAME, and the set of permitted names has to be
 * the same in three places: the stylesheet that declares them, the TypeScript the inspector
 * offers, and the CHECK constraint the database enforces. Hand-maintaining three copies is how
 * a section ends up storing `--md-gone`, which CSS renders as transparent — a section with no
 * background, which looks like a layout bug rather than a deleted token.
 *
 * So the stylesheet is the source and the other two are derived from it.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

/** The seven surface tokens, in the order 10 §2.1 lists them. Order is meaningful: the first
 *  is what a section stores as NULL, and the inspector's advanced group follows it. */
const SURFACE_TOKENS = [
  "--md-ivory-soft",
  "--md-ivory",
  "--md-stone",
  "--md-emerald-deep",
  "--md-forest",
  "--md-green-dark",
  "--md-green-black",
] as const;

const NOTES: Record<string, string> = {
  "--md-ivory-soft": "page ground (the default when the section stores NULL)",
  "--md-ivory": "raised / alternating band",
  "--md-stone": "quiet divider band",
  "--md-emerald-deep": "primary dark surface",
  "--md-forest": "secondary dark surface",
  "--md-green-dark": "deep panel / image scrim base",
  "--md-green-black": "near-black ground, full-bleed editorial",
};

function main(): void {
  const css = readFileSync(resolve(process.cwd(), "src/styles/tokens.css"), "utf8");

  // Every token must actually be DECLARED in the stylesheet. Generating a constant for a
  // token nobody declared is the failure this script exists to prevent, one step earlier.
  const missing = SURFACE_TOKENS.filter((t) => !new RegExp(`^\\s*${t}:`, "m").test(css));
  if (missing.length > 0) {
    throw new Error(
      `These surface tokens are not declared in src/styles/tokens.css: ${missing.join(", ")}. ` +
        `A section storing one would render var(--md-gone) as transparent.`,
    );
  }

  const body = `// GENERATED by scripts/gen-background-tokens.ts from src/styles/tokens.css.
// Do not edit. Add a surface by declaring it in the stylesheet and in that script's list,
// then re-running the generator and the migration that widens
// chk_cms_sections_background_token.
//
// 11 §7.7: cms_sections.background_token and the background_token field on the banner, cta,
// heritage and newsletter blocks accept exactly these seven values or NULL. A hex value in
// the database is impossible rather than merely forbidden in prose.

export const BACKGROUND_TOKENS = [
${SURFACE_TOKENS.map((t) => `  "${t}", // ${NOTES[t]!}`).join("\n")}
] as const;

export type BackgroundToken = (typeof BACKGROUND_TOKENS)[number];

/** The default when a section stores NULL. */
export const DEFAULT_BACKGROUND_TOKEN: BackgroundToken = BACKGROUND_TOKENS[0];

/** The \`data-surface\` value for a token — the stylesheet keys its surface blocks on this. */
export function surfaceFor(token: BackgroundToken | null): string {
  return (token ?? DEFAULT_BACKGROUND_TOKEN).replace(/^--md-/, "");
}

export function isBackgroundToken(value: string): value is BackgroundToken {
  return (BACKGROUND_TOKENS as readonly string[]).includes(value);
}
`;

  mkdirSync(resolve(process.cwd(), "src/lib/cms"), { recursive: true });
  writeFileSync(resolve(process.cwd(), "src/lib/cms/backgroundTokens.ts"), body);
  console.log(`✓ background tokens: ${String(SURFACE_TOKENS.length)} surfaces`);
}

main();
