import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  BACKGROUND_TOKENS,
  DEFAULT_BACKGROUND_TOKEN,
  surfaceFor,
  isBackgroundToken,
} from "@/lib/cms/backgroundTokens";
import { declarationsIn } from "../support/colour";

/**
 * Commissioned by 10 §2.1 and 11 §7.7 — **three copies of one list must be one list.**
 *
 * A section's surface is stored as a token NAME, and the permitted set has to be identical in
 * the stylesheet that declares them, the TypeScript the inspector offers, and the CHECK
 * constraint the database enforces. Three hand-maintained copies is how a section ends up
 * storing `--md-gone`, which CSS renders as **transparent** — a section with no background,
 * which reads as a layout bug rather than as a deleted token, and which nobody traces back to
 * a stylesheet edit made three weeks earlier.
 */
const CSS = readFileSync(resolve(process.cwd(), "src/styles/tokens.css"), "utf8");
const DECLARED = declarationsIn(CSS);

describe("the stored surface vocabulary is exactly the declared one", () => {
  it("is seven tokens", () => {
    expect(BACKGROUND_TOKENS).toHaveLength(7);
  });

  it("every stored token is DECLARED in tokens.css", () => {
    // The direction that matters most: a token the CMS can store but the stylesheet does not
    // define renders as nothing at all.
    for (const token of BACKGROUND_TOKENS) {
      expect(DECLARED.has(token), `${token} is offered by the CMS but not declared`).toBe(true);
    }
  });

  it("every token has a [data-surface] block that sets a background", () => {
    // Declaring the custom property is not enough: a section applies its surface by
    // `data-surface`, and a token with no matching block would set no background and inherit
    // whatever it happened to sit inside.
    for (const token of BACKGROUND_TOKENS) {
      const surface = surfaceFor(token);
      expect(CSS, `no [data-surface="${surface}"] block for ${token}`).toContain(
        `[data-surface="${surface}"]`,
      );
    }
  });

  it("the default is the page ground", () => {
    // A section that stores NULL is not "no background" — it is the page ground.
    expect(DEFAULT_BACKGROUND_TOKEN).toBe("--md-ivory-soft");
    expect(surfaceFor(null)).toBe("ivory-soft");
  });

  it("rejects a value outside the set, including a hex", () => {
    // The database refuses these too (chk_cms_sections_background_token). This is the
    // readable half: the inspector should never offer what the CHECK would reject.
    expect(isBackgroundToken("--md-ivory")).toBe(true);
    expect(isBackgroundToken("--md-gone")).toBe(false);
    expect(isBackgroundToken("#FCFAF5")).toBe(false);
    expect(isBackgroundToken("--md-green")).toBe(false); // a brand colour, never a surface
  });

  it("is GENERATED, not hand-edited", () => {
    // The generator is the reason the three copies stay one. A hand-edit would survive every
    // assertion above while silently decoupling this file from the stylesheet.
    const src = readFileSync(resolve(process.cwd(), "src/lib/cms/backgroundTokens.ts"), "utf8");
    expect(src.startsWith("// GENERATED by scripts/gen-background-tokens.ts")).toBe(true);
  });

  it("excludes the metallics and the brand green, which are never surfaces", () => {
    // 10 §2.1 rules 1 and 2. A gold background is an automatic review failure; making it
    // unstorable is better than making it forbidden in prose.
    for (const never of ["--md-gold-antique", "--md-champagne", "--md-green"]) {
      expect(BACKGROUND_TOKENS as readonly string[]).not.toContain(never);
    }
  });
});
